[workspace]
members = ["crates/*"]
default-members = ["crates/server"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
missing_debug_implementations = "deny"
unreachable_pub = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unused_extern_crates = "deny"
unused_import_braces = "deny"
unused_qualifications = "deny"
unused_results = "deny"
variant_size_differences = "deny"

[workspace.lints.clippy]
pedantic = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
exit = "deny"
get_unwrap = "deny"
panic_in_result_fn = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
missing_panics_doc = "deny"
doc_markdown = "deny"
ptr_as_ptr = "deny"
redundant_closure_for_method_calls = "deny"
cloned_instead_of_copied = "deny"
redundant_else = "deny"
semicolon_if_nothing_returned = "deny"
map_flatten = "deny"
map_identity = "deny"
exhaustive_structs = "deny"
single_match_else = "deny"

[workspace.dependencies]
anyhow = "1.0.102"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"
toml_edit = "0.23"
pulldown-cmark = "0.13.1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "signal", "macros", "fs"] }

# Server
axum = "0.8.8"
tower-http = { version = "0.6", features = ["fs", "cors", "set-header", "trace"] }
askama = { version = "0.15.4" }
utoipa = { version = "5.4", features = ["axum_extras", "chrono"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }

# Generator
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
url = "2.5"

# Internal
types = { path = "crates/types" }

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
