version: "3.8"
services:
  db:
    image: paradedb/paradedb:latest
    container_name: twir
    restart: unless-stopped
    environment:
      POSTGRES_DB: twir
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - paradedb_data:/var/lib/postgresql/data
      - ./twir_dump.sql:/docker-entrypoint-initdb.d/twir_dump.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d twir"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  paradedb_data:
    name: paradedb_data
networks:
  default:
    name: paradedb_network
