[phases.setup]
nixPkgs = ["chromium", "glib", "openssl", "sqlite", "file", "rustup"]
cmds = ["rustup default stable"]

[staticAssets]
assets = "./assets"

[phases.build]
cmds = [
  '. $HOME/.cargo/env && cargo build --release --workspace',
  'mkdir -p /app/bin',
  'cp target/release/server /app/bin/',
  'cp target/release/crawler /app/bin/',
  'ls -la /app/bin',
  'file /app/bin/server',
]

[start]
cmd = "/app/bin/server"
