-- Migration: Improve spellfix1 typo correction with transposition costs
--
-- The default spellfix1 edit distance function treats a transposition of two
-- adjacent characters (e.g. "linxu" -> "linux") as a delete + insert, which
-- costs 200. This means a simple finger-slip like typing "xu" instead of "ux"
-- scores WORSE than an unrelated word that happens to share a phonetic hash.
--
-- This migration introduces a cost table (spellfix_editcost) that assigns a
-- cost of 75 to any two-letter transposition — cheaper than a substitution
-- (150) but not free. The search_vocab virtual table is then recreated with
-- edit_cost_table=spellfix_editcost so that editdist3() is used in place of
-- the built-in fixed-cost function.
--
-- Result: "linxu" now correctly corrects to "linux" instead of "lingua".

-- Step 1: Create the editdist3 cost table.
--
-- The three wildcard rows set the default costs:
--   '?' -> ''  deletion  (100)
--   '' -> '?'  insertion (100)
--   '?' -> '?' substitution (150)
--
-- All 650 ordered pairs of distinct lowercase ASCII letters are then inserted
-- as transposition rules with cost 75, generated by a cross-join of the 26
-- letters with themselves.
CREATE TABLE IF NOT EXISTS spellfix_editcost (
    iLang INT,
    cFrom TEXT,
    cTo   TEXT,
    iCost INT
);

DELETE FROM spellfix_editcost;

-- Default costs
INSERT INTO spellfix_editcost VALUES (0, '?', '',  100); -- deletion
INSERT INTO spellfix_editcost VALUES (0, '',  '?', 100); -- insertion
INSERT INTO spellfix_editcost VALUES (0, '?', '?', 150); -- substitution

-- Transpositions: every ordered pair of distinct lowercase letters at cost 75.
-- Generated via a recursive CTE that produces the 26-letter alphabet, then
-- cross-joined to get all ab/ba pairs where a != b.
WITH alpha(c) AS (
    SELECT 'a' UNION ALL SELECT 'b' UNION ALL SELECT 'c' UNION ALL
    SELECT 'd' UNION ALL SELECT 'e' UNION ALL SELECT 'f' UNION ALL
    SELECT 'g' UNION ALL SELECT 'h' UNION ALL SELECT 'i' UNION ALL
    SELECT 'j' UNION ALL SELECT 'k' UNION ALL SELECT 'l' UNION ALL
    SELECT 'm' UNION ALL SELECT 'n' UNION ALL SELECT 'o' UNION ALL
    SELECT 'p' UNION ALL SELECT 'q' UNION ALL SELECT 'r' UNION ALL
    SELECT 's' UNION ALL SELECT 't' UNION ALL SELECT 'u' UNION ALL
    SELECT 'v' UNION ALL SELECT 'w' UNION ALL SELECT 'x' UNION ALL
    SELECT 'y' UNION ALL SELECT 'z'
)
INSERT INTO spellfix_editcost (iLang, cFrom, cTo, iCost)
SELECT 0, a.c || b.c, b.c || a.c, 75
FROM alpha a, alpha b
WHERE a.c != b.c;

-- Step 2: Drop and recreate search_vocab with the cost table enabled.
--
-- The edit_cost_table parameter tells spellfix1 to use editdist3() with
-- the named table instead of the built-in fixed-cost distance function.
-- This must be set at CREATE time; it cannot be changed afterwards.
DROP TABLE IF EXISTS search_vocab;

CREATE VIRTUAL TABLE search_vocab USING spellfix1(edit_cost_table=spellfix_editcost);

-- Step 3: Repopulate the vocabulary from all FTS indexes.
--
-- We insert via the virtual table interface (not directly into search_vocab_vocab)
-- so that spellfix computes the k1/k2 phonetic keys correctly.
CREATE VIRTUAL TABLE IF NOT EXISTS _sv_articles USING fts5vocab(articles_fts, row);
INSERT INTO search_vocab (word, rank)
    SELECT term, doc FROM _sv_articles
    WHERE length(term) >= 3 AND term GLOB '[a-z][a-z]*';
DROP TABLE _sv_articles;

CREATE VIRTUAL TABLE IF NOT EXISTS _sv_videos USING fts5vocab(videos_fts, row);
INSERT INTO search_vocab (word, rank)
    SELECT term, doc FROM _sv_videos
    WHERE length(term) >= 3 AND term GLOB '[a-z][a-z]*';
DROP TABLE _sv_videos;

CREATE VIRTUAL TABLE IF NOT EXISTS _sv_podcasts USING fts5vocab(podcast_episodes_fts, row);
INSERT INTO search_vocab (word, rank)
    SELECT term, doc FROM _sv_podcasts
    WHERE length(term) >= 3 AND term GLOB '[a-z][a-z]*';
DROP TABLE _sv_podcasts;

CREATE VIRTUAL TABLE IF NOT EXISTS _sv_talks USING fts5vocab(talks_fts, row);
INSERT INTO search_vocab (word, rank)
    SELECT term, doc FROM _sv_talks
    WHERE length(term) >= 3 AND term GLOB '[a-z][a-z]*';
DROP TABLE _sv_talks;