//! Cookie banner selectors for removing consent dialogs

/// Comprehensive list of cookie banner selectors
pub static COOKIE_BANNER_SELECTORS: &[&str] = &[
    // Generic cookie banner patterns
    "#lightbox",
    "#cookie-banner",
    ".cookie-banner",
    "#cookieConsent",
    ".cookie-consent",
    "[class*='cookie-consent']",
    "[id*='cookie-consent']",
    "[class*='cookie-notice']",
    "[id*='cookie-notice']",
    "[class*='cookie-policy']",
    "[id*='cookie-policy']",
    ".CookieConsent",
    "#pz-gdpr",
    // TrustArc
    "#truste-consent-content",
    ".truste-consent-content",
    "#truste-consent-track",
    // Quantcast
    ".qc-cmp2-container",
    // Borlabs
    "#BorlabsCookieBox",
    // ConsentManager.net
    "#cmpbox",
    // Cookiebot
    "#CybotCookiebotDialog",
    // Complianz
    "#cmplz-cookiebanner-container",
    // OneTrust
    "#onetrust-consent-sdk",
    "#onetrust-banner-sdk",
    // Didomi
    "div#didomi-host",
    "#didomi-popup",
    "#didomi-notice",
    // Sourcepoint
    ".message-container > #notice",
    // iubenda
    "div#iubenda-cs-banner",
    // Osano
    "div.osano-cm-window",
    "div.osano-cm-dialog",
    // Cookie Control
    ".cc-window",
    ".cc-banner",
    // GDPR Cookie Consent
    "#cookie-law-info-bar",
    // EU Cookie Law
    ".eu-cookie-compliance-banner",
    // Cookie Notice
    "#cookie-notice",
    // Privacy Manager
    "#privacy-manager-popin",
    // Tarteaucitron
    "#tarteaucitronAlertBig",
    "#tarteaucitronWelcome",
    // Evidon
    "#_evidon-banner",
    "#_evidon_banner",
    // Custom implementations
    ".cookie-info",
    ".cookieinfo",
    "#cookieinfo",
    ".gdpr-banner",
    ".gdpr-popup",
    "#gdpr-popup",
    ".privacy-popup",
    "#privacy-popup",
    ".consent-banner",
    ".consent-popup",
    "#consent-popup",
    // Specific sites patterns
    ".fc-consent-root",
    ".fc-dialog-container",
    "#qc-cmp2-ui",
    "#qc-cmp2-container",
    ".sp_choice_type_11",
    "#cookiescript_injected",
    ".cky-consent-bar",
    "#cookie-disclosure",
    "#cookies-banner",
    ".cookies-notify",
    "#checkUPcookies",
    "#gdpr",
    ".cookiePolicy",
    "#cookieBar",
    "#cookiebanner",
    ".cookie-alert",
    "#tc-privacy-wrapper",
    "#ppms_cm_popup_overlay",
    "#shopify-pc__banner",
    ".cookie-notice-banner",
    "#__tealiumGDPRecModal",
    "#consent-modal",
    ".cookie-consent-spice",
    "#CookieBanner",
    ".bcpNotificationBar",
    "#gdpr-cookie-message",
    ".gdpr-banner",
    "#cookie-popover",
    "#cookies-bar",
    ".cookie-bar-wrap",
    "#cp-overlay",
    ".syno_cookie_element",
    ".privacyArea",
    "#tp-cookie",
    "#legal_notice",
    ".banner-lgpd-consent-container",
    "#cc-window",
    ".new-policy-box",
    "#cookiebanner",
    "#gdpr-banner",
    ".cookieLayer",
    "#klaro",
    "#info-modal",
    "#sd-cmp",
    ".cookie-pop",
    "#cmp-main",
    ".cookie-consent-overlay",
    "#pp_info",
    "#cookieConsentContainer",
    "#TRCO-application",
    "#consent-modal-yr73k",
    ".privacyArea",
    "#toast-container",
    "#js_reveal_cookie_content",
    "#cookie-consent-spice",
    "#modals",
    "#consent-wall",
    "#ccm-widget",
    "#kick__logi-container",
    ".cookie_consent_withings",
    "#cookieLB",
    "#cookieConsentBanner",
    "#modalTpl",
    "#cm",
    ".tarteaucitron",
    "#privacy-init-wall",
    ".tc-privacy-wrapper",
    "#GDPRConsentManagerContainer",
    "#as24-cmp-popup",
    ".lnc-firstRunPopup",
    "#cmp-modal",
    ".ccm--save-settings",
    "#cookieBtnAll",
    ".ei_btn_typ_validate",
    "#rgpd-btn-index-accept",
    ".cookie-banner-wrap",
    "#fancybox-container-1",
    ".js-cookie-banner",
    "#modal-cookie-info",
    ".disc-cp-modal__modal",
    ".fancybox-type-html",
    "main[data-consent-main]",
    "#cookie-consent-banner",
    "div.cookie-notice",
    "div.cookiebanner",
    ".CookieConsent__root___3GjU8",
    "#zdf-cmp-modal-content",
    ".consent-container",
    "#cl-consent",
    "#cookie-policy-btn",
    "[data-testid=\"cookie-banner\"]",
    "[data-testid=\"dl-cookieBanner\"]",
    "[data-tracking-opt-in-overlay=\"true\"]",
    "[data-consent-main]",
];
