[package]
name = "crawler"
edition = "2024"
publish = false

[dependencies]
types = { workspace = true }
storage = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dom_smoothie = { workspace = true }
env_logger = { workspace = true }
headless_chrome = { workspace = true }
indoc = { workspace = true }
log = { workspace = true }
pulldown-cmark = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }